published:
  - app:
      category: life
      application: weather
      name: 天气
      url: /service/weather
      publish_date: 2019-6-18
      desc: this is weather app

  - app:
      category: life
      application: backup-image
      name: 图片备份
      url: /service/image
      publish_date: 2019-6-18
      desc: this is image app

  - app:
      category: life
      application: stock
      name: 股票
      url: /service/stock
      publish_date: 2019-6-18
      desc: this is stock app

  - app:
      category: life
      application: constellation
      name: 星座运势
      url: /service/constellation
      publish_date: 2019-6-18
      desc: this is constellation app

  - app:
      category: life
      application: joke
      name: 笑话
      url: /service/joke
      publish_date: 2019-6-18
      desc: this is joke app

developing:

  - app:
      category: life
      application: joke
      name: 笑话
      url: /service/joke
      publish_date: 2019-6-18
      desc: this is joke app