# Generated by Django 2.2.1 on 2019-06-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='openid',
            new_name='open_id',
        ),
    ]
