# Generated by Django 2.2.1 on 2019-06-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20190611_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nikename',
            new_name='nickname',
        ),
    ]
