# Generated by Django 2.2.1 on 2019-06-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190611_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='focus_cities',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_constellations',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_stocks',
            field=models.TextField(default=[]),
        ),
    ]
